import { z } from "zod";
import { ANSWER_FIELD_DOCS, ANSWER_SCHEMAS } from "./answer-docs.ts";
import { assembleExample, type JsonSchema, renderInterface } from "./answer-format.ts";

/** Which operation asks for each answer, in the words the app uses for it. */
export const ANSWER_ASKED_BY: Record<keyof typeof ANSWER_SCHEMAS, string> = {
  StoryAnalysis: "**Analyse story** — reads the story and proposes the cast, places, props and chapters.",
  StoryRewrite: "**Rewrite story** — returns a rewritten story following your instruction.",
  ChapterOutline: "**Plan chapter**, first question — the chapter's scenes, before any pages.",
  ScenePages:
    "**Plan chapter**, one question per scene — that scene's pages and panels. For a film project these are shots, " +
    "for a vertical strip one panel per page with height and seam.",
  PanelPromptDraft: "**Prepare page prompts** — per-panel prompt text for the image model.",
  NarrationDraft: "**Generate narration** — the narrator's lines, tied to panels.",
  ImageDescription:
    "**Describe image** — what a reference image shows, by the aspects you asked for. Attach the image.",
  PanelCheck: "**Check panel** — a consistency check of finished artwork against its cast. Attach the image.",
};

/**
 * `docs/ANSWER_FORMATS.md`, generated. Every answer a keyless run can ask for: which operation asks, the commented
 * interface, and a complete example. Generated rather than written so it cannot drift from the schemas; a test fails
 * when the committed page and this output differ.
 */
export function answerReferenceMarkdown() {
  const parts = [
    "# Answer formats",
    "",
    "<!-- Generated by `bun scripts/answer-formats.ts` from packages/schemas. Do not edit by hand: a test compares",
    "     this file with the generated output. -->",
    "",
    "Every answer a paste-it-yourself run can ask for. Each prompt ends with the exact JSON Schema its answer is",
    "checked against; this page is the same thing made readable — every field, what goes in it, whether it can be",
    "left out, and an example value. The job page shows the same interface for the question in front of you. How the",
    "whole flow works is in [WITHOUT_API_KEYS](WITHOUT_API_KEYS.md).",
    "",
    "Examples describe one small story — *The Lamp at Vell*: Ines, a lighthouse engineer; Tomas, the old keeper; the",
    "lighthouse itself; Ines's weather notebook. Each complete example below is a valid answer, checked by the tests.",
    "",
    ...Object.keys(ANSWER_SCHEMAS).map((n) => `- [${n}](#${n.toLowerCase()})`),
    "",
  ];
  for (const [name, schema] of Object.entries(ANSWER_SCHEMAS)) {
    const key = name as keyof typeof ANSWER_SCHEMAS;
    const json = z.toJSONSchema(schema, { io: "input", unrepresentable: "any" }) as JsonSchema;
    const docs = ANSWER_FIELD_DOCS[key];
    parts.push(
      `## ${name}`,
      "",
      `Asked by ${ANSWER_ASKED_BY[key]}`,
      "",
      "```ts",
      renderInterface(name, json, docs),
      "```",
      "",
      "<details><summary>Complete example</summary>",
      "",
      "```json",
      JSON.stringify(assembleExample(json, docs), null, 2),
      "```",
      "",
      "</details>",
      "",
    );
  }
  return `${parts.join("\n").trimEnd()}\n`;
}
