import type { StyleDefinition } from "@openmanga/schemas";

const common = ["text", "lettering", "speech bubbles", "captions", "watermark", "logo", "signature"];

/** Our own original style presets. */
export const BUILTIN_STYLE_PRESETS: { key: string; name: string; definition: StyleDefinition }[] = [
  {
    key: "manhwa",
    name: "Manhwa",
    definition: {
      summary: "Contemporary Korean manhwa illustration with polished digital rendering.",
      lineTreatment: "Thin, confident, uniform-weight lineart with tapered ends.",
      colorPolicy: "Clean flat base colors with soft gradients; restrained saturation.",
      shading: "Two-tone cel shading with a soft airbrushed secondary shadow.",
      detailLevel: "High detail on faces and hands, simplified clothing folds.",
      faceRendering: "Slim faces, defined jawlines, expressive eyes with specular highlights, consistent proportions.",
      backgroundRendering: "Semi-realistic painted backgrounds, slightly desaturated behind characters.",
      motionEffects: "Subtle speed lines and blur only for action beats.",
      contrast: "Medium contrast, readable silhouettes.",
      screenTones: "None.",
      lighting: "Cinematic rim light and ambient bounce light.",
      exclusions: common,
    },
  },
  {
    key: "modern-webtoon",
    name: "Modern Webtoon",
    definition: {
      summary: "Bright vertical-scroll webtoon art optimized for phone readability.",
      lineTreatment: "Clean medium lines, slightly thicker outer contour.",
      colorPolicy: "Vivid, harmonious palette with strong character color identity.",
      shading: "Soft cel shading with gentle glow effects.",
      detailLevel: "Moderate; clarity over texture.",
      faceRendering: "Large readable expressions, consistent face shapes.",
      backgroundRendering: "Simplified gradients or soft-focus environments.",
      motionEffects: "Sparkle, glow and soft motion trails when fitting.",
      contrast: "High readability at small sizes.",
      screenTones: "None.",
      lighting: "Bright, even key light.",
      exclusions: common,
    },
  },
  {
    key: "shonen",
    name: "Shonen Manga",
    definition: {
      summary: "Energetic Japanese shonen manga art.",
      lineTreatment: "Bold dynamic ink lines with strong weight variation.",
      colorPolicy: "Primarily black and white ink.",
      shading: "Hatching and solid blacks.",
      detailLevel: "Dense in action, clean in dialogue scenes.",
      faceRendering: "Spiky hair shapes, determined expressions, clear eye shapes.",
      backgroundRendering: "Perspective backgrounds, speed lines during action.",
      motionEffects: "Heavy speed lines, impact bursts.",
      contrast: "Strong black/white contrast.",
      screenTones: "Classic dot screentones for mid-values.",
      lighting: "Dramatic directional light.",
      exclusions: common,
    },
  },
  {
    key: "seinen",
    name: "Seinen Manga",
    definition: {
      summary: "Mature, grounded seinen manga illustration.",
      lineTreatment: "Fine detailed pen lines, realistic anatomy.",
      colorPolicy: "Black and white with grey tones.",
      shading: "Cross-hatching and realistic tonal rendering.",
      detailLevel: "Very high environmental and anatomical detail.",
      faceRendering: "Realistic proportions, subtle micro-expressions.",
      backgroundRendering: "Photographic-reference level backgrounds.",
      motionEffects: "Minimal, restrained.",
      contrast: "High, moody.",
      screenTones: "Gradient and texture tones.",
      lighting: "Naturalistic, low-key lighting.",
      exclusions: common,
    },
  },
  {
    key: "shojo",
    name: "Shojo Manga",
    definition: {
      summary: "Elegant, emotional shojo manga art.",
      lineTreatment: "Delicate thin lines, flowing hair strands.",
      colorPolicy: "Black and white with soft tones, or pastel colors.",
      shading: "Light screentones, sparkles.",
      detailLevel: "Ornate details on eyes, hair, and clothing.",
      faceRendering: "Large luminous eyes, soft features.",
      backgroundRendering: "Flowers, bubbles and abstract mood backgrounds for emotional beats.",
      motionEffects: "Floating petals and sparkles.",
      contrast: "Soft, low contrast.",
      screenTones: "Soft gradient tones.",
      lighting: "Dreamy diffuse light.",
      exclusions: common,
    },
  },
  {
    key: "dark-fantasy",
    name: "Dark Fantasy",
    definition: {
      summary: "Gritty dark fantasy illustration.",
      lineTreatment: "Scratchy textured ink lines.",
      colorPolicy: "Muted desaturated palette with deep blacks and accent reds or golds.",
      shading: "Heavy chiaroscuro.",
      detailLevel: "Intricate armor, ruins, and textures.",
      faceRendering: "Sharp gaunt features, intense eyes.",
      backgroundRendering: "Atmospheric fog, ruined architecture.",
      motionEffects: "Embers, smoke, dark energy wisps.",
      contrast: "Very high.",
      screenTones: "Grain texture.",
      lighting: "Low-key, torch or moonlight.",
      exclusions: common,
    },
  },
  {
    key: "action",
    name: "Action",
    definition: {
      summary: "High-impact action comic illustration.",
      lineTreatment: "Bold kinetic lines, exaggerated foreshortening.",
      colorPolicy: "Saturated with punchy highlights.",
      shading: "Hard shadows.",
      detailLevel: "Focus detail on impact points.",
      faceRendering: "Intense expressions, consistent character features.",
      backgroundRendering: "Dynamic perspective, debris.",
      motionEffects: "Speed lines, impact frames, motion blur.",
      contrast: "High.",
      screenTones: "None.",
      lighting: "Dramatic rim and explosion light.",
      exclusions: common,
    },
  },
  {
    key: "romance",
    name: "Romance",
    definition: {
      summary: "Soft romantic illustration.",
      lineTreatment: "Soft thin lines.",
      colorPolicy: "Warm pastels and blush tones.",
      shading: "Soft gradients.",
      detailLevel: "Detailed faces, hair and fashion.",
      faceRendering: "Attractive, gentle expressions, consistent faces.",
      backgroundRendering: "Bokeh, warm interiors, soft skies.",
      motionEffects: "Gentle sparkles.",
      contrast: "Low to medium.",
      screenTones: "None.",
      lighting: "Golden hour and warm glows.",
      exclusions: common,
    },
  },
  {
    key: "horror",
    name: "Horror",
    definition: {
      summary: "Unsettling horror comic illustration.",
      lineTreatment: "Uneven, nervous lines.",
      colorPolicy: "Sickly desaturated palette or stark monochrome.",
      shading: "Deep shadows swallowing detail.",
      detailLevel: "Disturbing details in focal points, obscured elsewhere.",
      faceRendering: "Wide eyes, tense expressions.",
      backgroundRendering: "Claustrophobic, dark, vignetted.",
      motionEffects: "Distortion, shaky lines.",
      contrast: "Extreme.",
      screenTones: "Noise and grain.",
      lighting: "Underlighting, single weak light source.",
      exclusions: common,
    },
  },
  {
    key: "minimal-anime",
    name: "Minimal Anime",
    definition: {
      summary: "Minimal clean anime style.",
      lineTreatment: "Clean simple lines.",
      colorPolicy: "Limited flat palette.",
      shading: "Single flat shadow tone.",
      detailLevel: "Low; clear shapes.",
      faceRendering: "Simple features, consistent shapes.",
      backgroundRendering:
        "Flat color and simple geometry, but every location feature from the reference stays present and recognizable.",
      motionEffects: "Minimal.",
      contrast: "Medium.",
      screenTones: "None.",
      lighting: "Flat even light.",
      exclusions: common,
    },
  },
  {
    key: "realistic",
    name: "Realistic",
    definition: {
      summary: "Photorealistic live-action look, like stills from a high-budget film shot on a cinema camera.",
      lineTreatment: "No outlines or ink lines; edges come from light, focus and material.",
      colorPolicy: "Natural, film-graded color with true-to-life skin tones.",
      shading: "Physically accurate light falloff, soft shadows and ambient occlusion.",
      detailLevel: "Real-world detail: skin pores, fabric weave, wear and dirt on surfaces.",
      faceRendering:
        "Real human faces with natural proportions and asymmetry, believable skin, consistent identity across shots.",
      backgroundRendering: "Real locations and sets with depth of field.",
      motionEffects: "Natural motion blur only; no drawn effects.",
      contrast: "Cinematic, with detail kept in highlights and shadows.",
      screenTones: "None.",
      lighting: "Motivated practical and natural light, cinematic key, fill and rim.",
      exclusions: [
        ...common,
        "drawing, illustration, painting or comic look",
        "anime or cartoon features",
        "outlines, ink lines or cel shading",
        "3D render, CGI or video-game look",
        "plastic, airbrushed skin",
      ],
      photoreal: true,
    },
  },
];

export const COLOR_MODE_DIRECTIVES = {
  full_color: "Full color artwork.",
  grayscale: "Grayscale artwork only, no color, full range of grey values.",
  bw_manga: "Black and white manga ink artwork with screentones, no color and no grey wash.",
} as const;
