import { z } from "zod";
import { annotationsFor, type McpTool } from "./registry.ts";
import { MCP_SCOPES } from "./scopes.ts";
import { MCP_TOOLS } from "./tools/index.ts";

const json = (schema: z.ZodType) =>
  JSON.stringify(z.toJSONSchema(schema, { io: "input", unrepresentable: "any" }), null, 2);

/** Which tools need a scope, for the scope catalogue. */
const toolsFor = (scope: string) =>
  MCP_TOOLS.filter((t) => t.scopes.includes(scope as never)).map((t) => `\`${t.name}\``);

function toolSection(t: McpTool) {
  const a = annotationsFor(t);
  return [
    `### ${t.name}`,
    "",
    t.description,
    "",
    `- **Scopes:** ${t.scopes.length ? t.scopes.map((s) => `\`${s}\``).join(", ") : "none (any authenticated connection)"}${t.scopesFor ? " — per action, see description" : ""}`,
    `- **Sensitivity:** ${t.sensitivity}${t.classify && t.sensitivity !== "read" ? " (the most sensitive action; each call is classified by what it does)" : ""}`,
    `- **Idempotent:** ${t.idempotent ? "yes" : "no"}${t.input.shape.idempotencyKey ? " — accepts `idempotencyKey`" : ""}`,
    `- **Annotations:** readOnly=${a.readOnlyHint}, destructive=${a.destructiveHint}, idempotent=${a.idempotentHint}, openWorld=${a.openWorldHint}`,
    t.actionKeys.length ? `- **Approval action keys:** ${t.actionKeys.map((k) => `\`${k}\``).join(", ")}` : "",
    t.routes.length ? `- **Wraps:** ${t.routes.map((r) => `\`${r}\``).join(", ")}` : "",
    "",
    "<details><summary>Input schema</summary>",
    "",
    "```json",
    json(t.input),
    "```",
    "",
    "</details>",
    "",
    "<details><summary>Output (<code>data</code>) schema</summary>",
    "",
    "```json",
    json(t.output),
    "```",
    "",
    "</details>",
    "",
  ]
    .filter((l, i, all) => l !== "" || all[i - 1] !== "")
    .join("\n");
}

/**
 * `docs/MCP_TOOLS.md`, generated from the tool registry and the scope catalogue, so the documentation cannot drift
 * from what the server registers. A test fails when the committed page differs.
 */
export function mcpCatalogueMarkdown() {
  const parts = [
    "# MCP tool and scope catalogue",
    "",
    "<!-- Generated by `bun scripts/mcp-docs.ts` from apps/api/src/mcp. Do not edit by hand: a test compares this",
    "     file with the generated output. -->",
    "",
    "How to connect, approvals, manual mode and the error model are in [MCP](MCP.md).",
    "",
    "Every successful result is `{ ok: true, status, data?, approval?, requestId, links? }`: `status` is `completed`",
    "(then `data` has the shape below) or `pending_approval` (then `approval` says what waits for the user). Errors are",
    "tool results with `isError: true` and `{ ok: false, error: { code, message, status, details?, requestId } }`.",
    "",
    "## Scopes",
    "",
    "| Scope | Consent description | Tools |",
    "| --- | --- | --- |",
    ...Object.entries(MCP_SCOPES).map(([s, d]) => `| \`${s}\` | ${d} | ${toolsFor(s).join(", ")} |`),
    "",
    "`get_server_info`, `get_answer_schema`, `describe_api` and `get_approval_request` (for the connection's own",
    "requests) need no scope.",
    "",
    "## Tools",
    "",
    "| Tool | Sensitivity | Scopes |",
    "| --- | --- | --- |",
    ...MCP_TOOLS.map(
      (t) => `| [\`${t.name}\`](#${t.name}) | ${t.sensitivity} | ${t.scopes.map((s) => `\`${s}\``).join(" ") || "—"} |`,
    ),
    "",
    ...MCP_TOOLS.map(toolSection),
  ];
  return `${parts.join("\n").trimEnd()}\n`;
}
